# Generated by Django 4.1.2 on 2023-02-19 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("retail", "0003_contractor_trader_id"),
        ("factory", "0002_factory_debt"),
    ]

    operations = [
        migrations.AddField(
            model_name="factory",
            name="contractor_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="retail.contractor",
            ),
        ),
    ]
