# Generated by Django 4.1.2 on 2023-02-19 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("trader", "0001_initial"),
        ("retail", "0002_retail_debt"),
    ]

    operations = [
        migrations.AddField(
            model_name="contractor",
            name="trader_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="trader.trader",
            ),
        ),
    ]
